services:
  mysql:
    image: mysql:8
    container_name: mysql-local  # 컨테이너 이름 지정
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"  # 호스트의 3306 포트를 컨테이너의 3306 포트로 매핑
    volumes:
      - mysql_data:/var/lib/mysql  # 데이터 지속성을 위해 볼륨 설정
    networks:
      - mysql-network  # 사용자 정의 네트워크를 사용
    env_file:
      - .env  # .env 파일을 참조

volumes:
  mysql_data:  # mysql 데이터 저장용 볼륨 생성

networks:
  mysql-network:  # 사용자 정의 네트워크 설정
    driver: bridge  # 기본적으로 bridge 네트워크 드라이버 사용