"""add patient table

Revision ID: 39c0f18abb5a
Revises: 2cfd7c36bf4d
Create Date: 2025-01-15 15:20:35.695340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c0f18abb5a'
down_revision: Union[str, None] = '2cfd7c36bf4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
