"""add patient table

Revision ID: f093f0966b9c
Revises: 39c0f18abb5a
Create Date: 2025-01-15 15:21:57.813347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f093f0966b9c'
down_revision: Union[str, None] = '39c0f18abb5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Patient',
    sa.Column('pid', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('patient_name', sa.String(length=36), nullable=False),
    sa.Column('patient_age', sa.Integer(), nullable=False),
    sa.Column('birthdate', sa.DateTime(), nullable=False),
    sa.Column('result_status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('pid'),
    sa.UniqueConstraint('pid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Patient')
    # ### end Alembic commands ###
