"""user - add memo

Revision ID: 2cfd7c36bf4d
Revises: 2db35456b58c
Create Date: 2025-01-10 15:41:22.226530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cfd7c36bf4d'
down_revision: Union[str, None] = '2db35456b58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('memo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'memo')
    # ### end Alembic commands ###
